project_id = "rdstyfaveeokocztayri"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.payment-recovery]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.stripe-callback]
verify_jwt = false

[functions.stripe-status]
verify_jwt = false

[functions.stripe-insights]
verify_jwt = false

[functions.stripe-monitor]
verify_jwt = false
